// <auto-generated />
namespace UCRMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class imran01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imran01));
        
        string IMigrationMetadata.Id
        {
            get { return "201912131616112_imran-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
